import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Azeret_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./navbar/page";

const inter = Inter({ subsets: ["latin"] });

const azeretMono = Azeret_Mono({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Tolu_Jacob portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={azeretMono.className}>
        <Navbar />
        <div className="h-full">{children}</div>
      </body>
    </html>
  );
}
